
baseURL = "https://abhinavbabu.in/blog/"
languageCode = "en-us"
title = "Blogs of Abhinav Babu"

[permalinks]
posts = "/:slug/"

[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true